import '../styles/global.scss';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>ClubHouse</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
