import '../styles/global.scss';
import Head from 'next/head';
import { store, wrapper } from '../redux/store';
import { Provider } from 'react-redux';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>ClubHouse</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

export default wrapper.withRedux(MyApp);
