import Head from 'next/head';
import { WelcomeStep } from '../components/steps/WelcomeStep';

export default function Home() {
  return (
    <div>
      <Head>
        <title>ClubHouse</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <WelcomeStep />
    </div>
  );
}
